spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  batch:
    job:
      enabled: false
  port: 8091
